// Generated by CoffeeScript 1.9.0
(function() {
  $(function($) {
    var router, routers, scrollTo, switchView, wow;
    scrollTo = function(h) {
      return $('html, body').animate({
        scrollTop: h
      }, 1000);
    };
    $('.main-navigation .btn').click(function(e) {
      console.log("click");
      return scrollTo($($(this).data("goto")).offset().top - 60);
    });
    switchView = function(eleID, subCallback) {
      var $active, $prepare;
      $prepare = $("#" + eleID);
      $active = $(".LargePage.active");
      console.log("Routing!!", eleID, $active);
      return $active.fadeOut({
        complete: function() {
          $active.removeClass("active");
          $('html, body').scrollTop(0);
          return $prepare.fadeIn({
            complete: function() {
              $prepare.addClass("active");
              console.log($("#" + eleID));
              if (subCallback) {
                return subCallback();
              }
            }
          });
        }
      });
    };
    wow = new WOW();
    wow.init();
    $('[data-toggle="tooltip"]').tooltip();
    router = new Simrou();
    routers = {};
    routers.memberRouter = router.addRoute('/About');
    routers.memberRouter.get(function(event, params) {
      return switchView("About");
    });
    routers.mainRouter = router.addRoute('/Main');
    routers.mainRouter.get(function(event, params) {
      return switchView("Main");
    });
    routers.mainSubRouter = router.addRoute('/Main/:subelement');
    routers.mainSubRouter.get(function(event, params) {
      if ($(".LargePage.active").attr("id") === "Main") {
        return scrollTo($("#" + params.subelement).offset().top - 60);
      } else {
        return switchView("Main", function() {
          return scrollTo($("#" + params.subelement).offset().top - 60);
        });
      }
    });
    routers.reserveRouter = router.addRoute('/Reserve');
    routers.reserveRouter.get(function(event, params) {
      return switchView("Reserve");
    });
    return router.start();
  });

}).call(this);
