// Generated by CoffeeScript 1.9.0
(function() {
  var init;

  init = function() {
    var router, routers, scrollTo, switchView, wow;
    $("#prepare").fadeIn();
    scrollTo = function(h) {
      return $('html, body').animate({
        scrollTop: h
      }, 1000);
    };
    $('.main-navigation .btn').click(function(e) {
      return scrollTo($($(this).data("goto")).offset().top - 60);
    });
    switchView = function(eleID, subCallback) {
      var $active, $prepare;
      $prepare = $("#" + eleID);
      $active = $(".LargePage.active");
      return $active.fadeOut({
        complete: function() {
          $active.removeClass("active");
          $('html, body').scrollTop(0);
          return $prepare.fadeIn({
            complete: function() {
              $prepare.addClass("active");
              if (subCallback) {
                return subCallback();
              }
            }
          });
        }
      });
    };
    wow = new WOW();
    wow.init();
    $('#_mag').magnify({
      speed: 200,
      src: 'img/main/plan/cover_small.png'
    });
    $('[data-toggle="tooltip"]').tooltip();
    router = new Simrou();
    routers = {};
    routers.memberRouter = router.addRoute('/About');
    routers.memberRouter.get(function(event, params) {
      return switchView("About");
    });
    routers.mainRouter = router.addRoute('/Main');
    routers.mainRouter.get(function(event, params) {
      return switchView("Main");
    });
    routers.mainSubRouter = router.addRoute('/Main/:subelement');
    routers.mainSubRouter.get(function(event, params) {
      if ($(".LargePage.active").attr("id") === "Main") {
        return scrollTo($("#" + params.subelement).offset().top - 60);
      } else {
        return switchView("Main", function() {
          return scrollTo($("#" + params.subelement).offset().top - 60);
        });
      }
    });
    routers.reserveRouter = router.addRoute('/Reserve');
    routers.reserveRouter.get(function(event, params) {
      return switchView("Reserve");
    });
    return router.start();
  };

  (function(i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] || function() {
      (i[r].q = i[r].q || []).push(arguments);
    };
    i[r].l = 1 * new Date;
    a = s.createElement(o);
    m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m);
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

  ga('create', 'UA-62541029-1', 'auto');

  ga('send', 'pageview');

  document.onreadystatechange = function() {
    if (document.readyState === 'complete') {
      init();
    }
  };

}).call(this);
